### ISSUE TITLE
Repository needs to be moved to purescript organization.

### ISSUE THREAD

**Issue by raichoo** [purescript-contrib/purescript-vim#25]
This repository needs to be moved, anything that needs to be done to do so should end up
here.

/cc @paf31

**Comment by coot** [comment]
And please add maintainer rights to me, as I agreed to take that role on twitter.

**Comment by raichoo** [comment]
I really want to get this moved to the purescript org first. Please nudge @paf31 a bit as well. I've wanted to move the repo maybe a year ago but it never happened. This time I mean business ;)

**Comment by paf31** [comment]
I've sent you both invites to `purescript-contrib`.

**Comment by raichoo** [comment]
@paf31 I need permission to create a repo, otherwise I cannot transfer this one.

**Comment by paf31** [comment]
Try now?

**Comment by paf31** [comment]
Seems to have worked :)
