### ISSUE TITLE
Choose a maintainer

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-vim#28]
and add the maintainer badge to the readme.

**Comment by raichoo** [comment]
I think @coot and @arthur-xavier both need commit access to this repo.

**Comment by paf31** [comment]
Invites sent, thanks.

**Comment by coot** [comment]
Thanks @paf31. I will add the maintainer badge later this evening.

**Comment by coot** [comment]
@paf31 I need write permission for this repo.

**Comment by paf31** [comment]
Done, sorry.
