### ISSUE TITLE
Slow performance on NeoVim 0.2

### ISSUE THREAD

**Issue by rix501** [purescript-contrib/purescript-vim#45]
When entering text in nvim i see a real slow down after entering 1-2 characters (my guess is autocomplete?).

It works better in Vim but would love for it to work in nvim too.

Thanks and I really appreciate the work you've done so far!

**Comment by coot** [comment]
Can you check this with only purescript-vim enabled and with just purescript-vim and psc-ide-vim?

Do you use some plugin to automatically trigger completion (or does neovim do that)?

**Comment by coot** [comment]
Please reopen if this is still relevant.
