### ISSUE TITLE
Highlighting explicit types in multiline import

### ISSUE THREAD

**Issue by unclechu** [purescript-contrib/purescript-vim#53]
![screenshot from 2018-02-16 04-38-18](https://user-images.githubusercontent.com/799353/36286850-5c308b04-12d3-11e8-9083-81390bd49ba2.png)
![screenshot from 2018-02-16 04-38-07](https://user-images.githubusercontent.com/799353/36286855-614b6b90-12d3-11e8-8b7e-b174b02f122e.png)

**Comment by unclechu** [comment]
`as` keyword also have this issue:
![screenshot from 2018-02-18 04-33-23](https://user-images.githubusercontent.com/799353/36346682-f544563a-1464-11e8-8dea-7c9512beb7af.png)
![screenshot from 2018-02-18 04-33-15](https://user-images.githubusercontent.com/799353/36346683-f7ff7cba-1464-11e8-90d5-1cc2faa0c2fe.png)

**Comment by unclechu** [comment]
Also if I just rename `import` to `module` it goes okay (maybe some parts of regex from `module` could be taken to fix `import` regex).
![screenshot from 2018-02-22 03-23-28](https://user-images.githubusercontent.com/799353/36508966-f5a78ed0-177f-11e8-8f21-e3c6e7d31caa.png)
![screenshot from 2018-02-22 03-23-37](https://user-images.githubusercontent.com/799353/36508973-f83629d6-177f-11e8-91ab-943c87fcb3f7.png)

**Comment by coot** [comment]
Please try the new version. It now consistently highlights classes, kinds, and functions within import and module syntax groups.

**Comment by unclechu** [comment]
@coot now I have both this issue and new one, all module names have similar color as `import`/`module` keyword.
![screenshot from 2018-03-11 18-55-28](https://user-images.githubusercontent.com/799353/37254300-cfcb735c-255d-11e8-8960-5ca521f2b01c.png)
![screenshot from 2018-03-11 18-55-35](https://user-images.githubusercontent.com/799353/37254301-d1555940-255d-11e8-95d1-ff66d07ab231.png)
So, I guess this issue supposed to be reopened.

**Comment by coot** [comment]
The bottom screenshare is how it is supposed to look like. You might differentiate the `import` and `module` by having different colours for `purscriptImportKeyword` (by default linked to `purescriptKeyword`) and `purescriptModuleName` (by default linked to `Include`) highlight classes.

The top one looks different here, `ReactClass` and other that start with an uppercase letter have `purescritpConstructor` syntax group and other have `purescriptIdentifier`.  It's a bit different when they are in the same line (which should be fixed), but still the default highlighting is consistent.
