### ISSUE TITLE
Option to disable indentation

### ISSUE THREAD

**Issue by elliotdavies** [purescript-contrib/purescript-vim#66]
It would be nice to have a setting that disables any auto-indentation at all, leaving the plugin as just a syntax highlighter.

If this sounds good, I'm happy to do the work and submit a PR!

**Comment by vladciobanu** [comment]
I would also like this myself! Would you still be up to PR it, or can I?

**Comment by elliotdavies** [comment]
@vladciobanu Please, go for it! 😁
