### ISSUE TITLE
Natural transformations

### ISSUE THREAD

**Issue by samhh** [purescript-contrib/purescript-vim#67]
Defined in [PureScript's prelude](https://pursuit.purescript.org/packages/purescript-prelude/3.1.0/docs/Data.NaturalTransformation) is the `NaturalTransformation` type, which is basically a shorthand from `f a -> g a` to `f ~> g`.

The `~>` operator does not seem to be getting the same highlighting as `->` and `=>`.

**Comment by vladciobanu** [comment]
There is a distinction between `->`, `=>` and `~>`. The latter is user-defined (even if it's in Prelude, it's not something the compiler is aware of).

The vim Haskell plugin, OTOH, just highlights all operators the same.

I would be okay with both options, but not really okay with just picking a few extra operators to add to the list. What do you think?

**Comment by samhh** [comment]
I suppose highlighting all operators the same is preferable provided that won't create bigger edge case problems?

**Comment by vladciobanu** [comment]
Not sure, but I will look into it sometime within the next week or so!

**Comment by toastal** [comment]
Fixed in https://github.com/purescript-contrib/purescript-vim/commit/cc511bdda7551c0ddac2f368bd129ac0bba87c1a.patch
