### ISSUE TITLE
Not same syntax highlight as Haskell

### ISSUE THREAD

**Issue by yemi** [purescript-contrib/purescript-vim#8]
Im using the solarized theme and in Haskell it looks like this:

![](http://ethanschoonover.com/solarized/img/screen-haskell-dark.png)

And in PureScript:

![purescript](https://cloud.githubusercontent.com/assets/416424/7801405/508ba782-0324-11e5-975b-30aace4cd083.png)

I really like the Haskell highlighting, im pretty new with vim but is there a way to use the same colors for PureScript or isnt it that simple?

**Comment by pierrebeaucamp** [comment]
+1

**Comment by arthur-xavier** [comment]
Hey @yemi and @pierrebeaucamp, could you check out the latest version of the plugin and see if it solves the problem? Thanks :)

**Comment by coot** [comment]
Closing since there is no feedback. Please reopen if you still experience this.
