### ISSUE TITLE
Find new maintainer

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-vim#88]
This repo was previously maintained by Evie but has fallen out of maintenance. If someone would like to take this over, let me know.

@toastal, since you've submitted 3 PRs to this repo, perhaps you would like that? At the very least, you'd be able to merge your PRs.

**Comment by toastal** [comment]
I would with some reluctance. a) I'm not a very strong VimL user (that is to say barely at all) and b) I dislike dealing with Microsoft GitHub

However, I am passionate about (Neo)Vim and PureScript so maybe I'm the best person for the job, at least for now.

**Comment by jamesdbrock** [comment]
Thanks @toastal ! You're the maintainer now. :heart:
