### ISSUE TITLE
Conceal for lambdas happens when it shouldn't 

### ISSUE THREAD

**Issue by Mateiadrielrafael** [purescript-contrib/purescript-vim#90]
The conceal for lambdas happens even if I use the tuple operator (/\\), which looks weird:
![image](https://user-images.githubusercontent.com/39400800/210549945-79db4aa4-fb03-4a9b-bcc4-edcdf0a7eef2.png)

**Comment by toastal** [comment]
Similar has happened with `>>=` that I wasn't seeing originally. I'll take a look at it na.

**Comment by toastal** [comment]
@Mateiadrielrafael can you test `main` I believe [this commit](https://github.com/purescript-contrib/purescript-vim/commit/95932f6d2b0df488f74839ff05b8169de8d1d55e) should cover it.

**Comment by prescientmoon** [comment]
Seems to work

**Comment by triallax** [comment]
A similar issue occurs with `==>`.

**Comment by toastal** [comment]
`>>=` as well I believe. I'm not yet entirely sure how the Haskell/Idris/OCaml concealers are _doing it_ when the code is basically copypasta.
